replicaCount: 4

image:
  repository: 694310032079.dkr.ecr.us-east-2.amazonaws.com/prueba-core
  tag: latest

service:
  port: 80
  targetPort: 3000

rollout:
  canary:
    enabled: true
    steps:
      - weight: 25
      - weight: 50

analysis:
  enabled: true
  errorRateThreshold: 0.05
