apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-metrics-rollout.fullname" . }}
  labels:
    app: rollout-demo
spec:
  selector:
    app: {{ include "demo-metrics-rollout.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
